import numpy as np

BASE_TRACK_VIEW_WIDTH = 800
BASE_TRACK_VIEW_HEIGHT = 600
TRACK_SCALE = 2

TRACK_VIEW_WIDTH = BASE_TRACK_VIEW_WIDTH * TRACK_SCALE
TRACK_VIEW_HEIGHT = BASE_TRACK_VIEW_HEIGHT * TRACK_SCALE

TOP_UI_MARGIN = 85
SIDE_MARGIN = 40
BOTTOM_MARGIN = 35

WINDOW_WIDTH = TRACK_VIEW_WIDTH + SIDE_MARGIN * 2
WINDOW_HEIGHT = TRACK_VIEW_HEIGHT + TOP_UI_MARGIN + BOTTOM_MARGIN

TRACK_OFFSET_X = SIDE_MARGIN
TRACK_OFFSET_Y = TOP_UI_MARGIN

TRACK_CENTER_X = TRACK_VIEW_WIDTH // 2
TRACK_CENTER_Y = TRACK_VIEW_HEIGHT // 2
TRACK_WIDTH = 50
TRACK_LENGTH = 560
TRACK_HEIGHT = 340
BORDER_THICKNESS = 4

CAR_START_X = TRACK_CENTER_X
CAR_START_Y = TRACK_CENTER_Y - 130

FPS = 60

RAY_COUNT = 21
RAY_FOV = np.pi
RAY_MAX_DISTANCE = 220
RAY_STEP = 4

DRAW_RAYS = True
