import numpy as np

BASE_TRACK_VIEW_WIDTH = 800
BASE_TRACK_VIEW_HEIGHT = 600
TRACK_SCALE = 2

TRACK_VIEW_WIDTH = BASE_TRACK_VIEW_WIDTH * TRACK_SCALE
TRACK_VIEW_HEIGHT = BASE_TRACK_VIEW_HEIGHT * TRACK_SCALE

TOP_UI_MARGIN = 85
SIDE_MARGIN = 40
BOTTOM_MARGIN = 35

WINDOW_WIDTH = TRACK_VIEW_WIDTH + SIDE_MARGIN * 2
WINDOW_HEIGHT = TRACK_VIEW_HEIGHT + TOP_UI_MARGIN + BOTTOM_MARGIN

TRACK_OFFSET_X = SIDE_MARGIN
TRACK_OFFSET_Y = TOP_UI_MARGIN

TRACK_CENTER_X = TRACK_VIEW_WIDTH // 2
TRACK_CENTER_Y = TRACK_VIEW_HEIGHT // 2
TRACK_WIDTH = 50
TRACK_LENGTH = 560
TRACK_HEIGHT = 340
BORDER_THICKNESS = 4

CAR_START_X = TRACK_CENTER_X
CAR_START_Y = TRACK_CENTER_Y - 130
CAR_START_ANGLE = 0

FPS = 60

RAY_COUNT = 21
RAY_FOV = np.pi
RAY_MAX_DISTANCE = 220
RAY_STEP = 4

DRAW_RAYS = True

STUCK_SPEED_KMH = 2.0
STUCK_POSITION_EPSILON = 1.0
STUCK_FRAME_LIMIT = 180
STUCK_GRACE_FRAMES = 90
BACKWARD_PROGRESS_LIMIT = 8
START_AREA_RADIUS = 50.0
MIN_LAP_PROGRESS_RATIO = 0.85
WRONG_WAY_ALIGNMENT_LIMIT = -0.25
WRONG_WAY_MOVEMENT_LIMIT = -0.10
WRONG_WAY_SPEED_KMH = 8.0
WRONG_WAY_FRAME_LIMIT = 45
